server:
   port: 9007
spring:
  application:
    name: PAGE-SERVICE
  datasource:
    url: jdbc:mysql:///hrm-page? serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
hrm:
  swagger:
    title: 页面静态化管理服务
    description: 页面静态管理服务接口文档

feign:
  hystrix:
    enabled: true
