server:
  port: 9008

spring:
  application:
    name: SYSTEM-SERVICE
  datasource:
    url: jdbc:mysql:///hrm-user? serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
hrm:
  swagger:
    title: 系统管理服务
    description: 系统管理服务接口文档